In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

In [3]:
dataset = pd. read_csv('Breast_Cancer_Data.csv')
dataset


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [4]:
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, 1].values

In [5]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [6]:
print(y)

['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'M'
 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
print(y.shape)
y = le.fit_transform(y)
y

(569,)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [8]:
print(y.shape)

(569,)


In [9]:
#creates models
def create_model(no_HL, HL_func, O_func):
    units = [8, 16, 32, 64, 128, 256]
    model = tf.keras.models.Sequential()
    model.add( tf.keras.layers.Flatten() )

    for i in range(no_HL):

        model.add( tf.keras.layers.Dense( units=units[i] , activation=HL_func ))

    model.add(tf.keras.layers.Dense(units=1, activation = O_func))

    return model

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#creates a group of models
def create_model_set(no_HL):
    model_l = []
    split_set = []

    #different hidden layer functions to test with
    HL_func = ['relu', 'leaky', 'relu', 'leaky', 'relu', 'leaky', 'relu', 'leaky', 'relu']

    #different output layer functions to test with
    O_func = ['sigmoid', 'tanh', 'softmax', 'sigmoid', 'tanh', 'softmax', 'sigmoid', 'tanh', 'softmax',]

    #different optimizers to test with
    optim = ['adam', 'adam', 'adam', 'RMSprop', 'RMSprop', 'RMSprop', 'Adagrad', 'Adagrad', 'Adagrad']

    #different random states to test with 
    rand_states = [0, 10, 15, 20, 25, 30, 35, 40, 45]

    #range(9) cus i made it 9 models per table
    for i in range(9):
        if HL_func[i] == 'leaky':
            model = create_model(no_HL, tf.keras.layers.LeakyReLU(alpha=0.3), O_func[i])
            model.compile(optimizer = optim[i], loss = 'binary_crossentropy', metrics = ['accuracy'])
            model_l.append(model)
        else:
            model = create_model(no_HL, HL_func[i], O_func[i])
            model.compile(optimizer = optim[i], loss = 'binary_crossentropy', metrics = ['accuracy'])
            model_l.append(model)

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = rand_states[i])
        split_set.append((X_train, X_test, y_train, y_test))
        
    return model_l, split_set
    

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
#trains models
def fit_models(models, split_sets, epoch, batch_size, table_no):
    accuracies = []
    for idx, (model, split_set) in enumerate(zip(models, split_sets)):
        sc = StandardScaler()
        X_train, X_test, y_train, y_test = split_set
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)
        model.fit(X_train, y_train, batch_size = batch_size, epochs = epoch)

        y_pred = model.predict(X_test)
        y_pred = (y_pred > 0.5) 
        cm = confusion_matrix(y_test, y_pred)
        score = accuracy_score(y_test, y_pred)
        accuracies.append(score)

        print(f'model {idx}, of table {table_no} is done')
    
    return accuracies
        

In [12]:
epochs = [100, 200, 300, 400, 500 ,600]
batch_sizes = [16, 32, 64, 128, 256, 256]
accuracies_list = []

#six cus i had 6 tables last time
for i in range(6):  
    models, split_sets = create_model_set(i+1)
    accuracies = fit_models(models, split_sets, epochs[i], batch_sizes[i], i)
    accuracies_list.append(accuracies)
    with open('accuracies3.txt', 'a') as f:
        f.write('\n'+str(accuracies))

Epoch 1/600
2/2 [==============================] - 1s 7ms/step - loss: 0.6726 - accuracy: 0.6374
Epoch 2/600
2/2 [==============================] - 0s 7ms/step - loss: 0.6415 - accuracy: 0.6374
Epoch 3/600
2/2 [==============================] - 0s 8ms/step - loss: 0.6094 - accuracy: 0.6374
Epoch 4/600
2/2 [==============================] - 0s 7ms/step - loss: 0.5768 - accuracy: 0.6374
Epoch 5/600
2/2 [==============================] - 0s 7ms/step - loss: 0.5444 - accuracy: 0.6374
Epoch 6/600
2/2 [==============================] - 0s 7ms/step - loss: 0.5123 - accuracy: 0.6396
Epoch 7/600
2/2 [==============================] - 0s 5ms/step - loss: 0.4787 - accuracy: 0.7121
Epoch 8/600
2/2 [==============================] - 0s 7ms/step - loss: 0.4450 - accuracy: 0.7890
Epoch 9/600
2/2 [==============================] - 0s 6ms/step - loss: 0.4106 - accuracy: 0.8220
Epoch 10/600
2/2 [==============================] - 0s 6ms/step - loss: 0.3798 - accuracy: 0.8440
Epoch 11/600
2/2 [===========